import Head from "next/head";
import Image from "next/image";
import {
  AppBar,
  Container,
  Toolbar,
  Button,
  Box,
  IconButton,
  Avatar,
} from "@mui/material";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useRouter } from "next/router";

export default function Home() {

  const router = useRouter();
  const handleLogout = () => {
    localStorage.removeItem("token");
    router.push("/auth/login");
  };

 
  return (
    <div className={styles.container}>
      <Head>
        <title> My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppBar sx={{ marginTop: 4, color: "red" }} position="static">
        <Container maxWidth="xl">
          <Toolbar disableGutters>
            <Box sx={{ flexGrow: 1 }}>
              <Link href="/" passHref>
                <Button sx={{ color: "white" }}>Ashik App</Button>
              </Link>
            </Box>

            <Box sx={{ ml: 15 }}>
              <Link href="/auth/login" passHref>
                <Button sx={{ ml: 2, color: "white" }}>Login</Button>
              </Link>
              <Link href="/auth/register" passHref>
                <Button sx={{ ml: 2, color: "white" }}>Register</Button>
              </Link>
            </Box>
            <Box sx={{ display: "flex", justifyContent: "flex-end", ml: 8 }}>
              <IconButton
                sx={{ color: "white" }}
                href="https://www.google.com"
                target="_blank"
              >
                <Avatar alt="Remy Sharp" src="/static/images/avatar/2.jpg" />
              </IconButton>
            </Box>

            <Box sx={{ ml: 2 }}>
              <Button onClick={handleLogout} sx={{ color: "white" }}>
                Logout
              </Button>
            </Box>
          </Toolbar>
        </Container>
      </AppBar>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my Web <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div>
          <h1>Welcome to Ashik Next.js App</h1>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
